name: 'repo-backup'
on:
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  repo-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo-backup-ipfs
        uses: Dhaiwat10/repo-backup-ipfs@v0.4
        with:
          web3storage_token: ${{ secrets.WEB3STORAGE_TOKEN }}