name: Zip and Commit

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  zip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip the folder
        run: |
          zip -r files/app/public/public-folder.zip files/app/public/*

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit ZIP to repository
        run: |
          git add files/app/public/public-folder.zip
          git commit -m "Add ZIP of public folder"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
