name: Zip and Commit

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  zip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip the contents of the public folder
        run: |
          # Navigate to the public directory
          cd files/app/public
          # Create a zip of the contents without including the folder itself
          zip -r ../../../public-folder.zip ./*

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit ZIP to repository
        run: |
          git add 3pad.zip
          git commit -m "Add ZIP of 3pad folder contents to root"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this line is correct
