name: Zip and Commit

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  zip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean up old ZIP files (if any)
        run: |
          # Remove any existing ZIP file to avoid conflicts or overwriting issues
          rm -f wp-content-folder.zip

      - name: Zip the contents of the wp-content folder
        run: |
          # Create a zip of the contents of the wp-content directory
          cd 3pad-playground/wp-content
          zip -r ../../wp-content-folder.zip .
        shell: bash

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit ZIP to repository
        run: |
          # Check for changes, only commit if there are changes to avoid unnecessary commits
          if [ -n "$(git status --porcelain)" ]; then
            git add wp-content-folder.zip
            git commit -m "Add ZIP of wp-content folder to root"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
